// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/binary_storage.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BinaryStorage_UploadBinary_FullMethodName   = "/storage.gophkeeper.BinaryStorage/UploadBinary"
	BinaryStorage_DownloadBinary_FullMethodName = "/storage.gophkeeper.BinaryStorage/DownloadBinary"
	BinaryStorage_ListBinaries_FullMethodName   = "/storage.gophkeeper.BinaryStorage/ListBinaries"
	BinaryStorage_DeleteBinary_FullMethodName   = "/storage.gophkeeper.BinaryStorage/DeleteBinary"
)

// BinaryStorageClient is the client API for BinaryStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BinaryStorageClient interface {
	UploadBinary(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BinaryChunk, BinaryRecordID], error)
	DownloadBinary(ctx context.Context, in *BinaryRecordID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BinaryChunk], error)
	ListBinaries(ctx context.Context, in *BinaryEmpty, opts ...grpc.CallOption) (*BinaryRecordList, error)
	DeleteBinary(ctx context.Context, in *BinaryRecordID, opts ...grpc.CallOption) (*BinaryEmpty, error)
}

type binaryStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewBinaryStorageClient(cc grpc.ClientConnInterface) BinaryStorageClient {
	return &binaryStorageClient{cc}
}

func (c *binaryStorageClient) UploadBinary(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BinaryChunk, BinaryRecordID], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BinaryStorage_ServiceDesc.Streams[0], BinaryStorage_UploadBinary_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BinaryChunk, BinaryRecordID]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryStorage_UploadBinaryClient = grpc.ClientStreamingClient[BinaryChunk, BinaryRecordID]

func (c *binaryStorageClient) DownloadBinary(ctx context.Context, in *BinaryRecordID, opts ...grpc.CallOption) (grpc.ServerStreamingClient[BinaryChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &BinaryStorage_ServiceDesc.Streams[1], BinaryStorage_DownloadBinary_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BinaryRecordID, BinaryChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryStorage_DownloadBinaryClient = grpc.ServerStreamingClient[BinaryChunk]

func (c *binaryStorageClient) ListBinaries(ctx context.Context, in *BinaryEmpty, opts ...grpc.CallOption) (*BinaryRecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryRecordList)
	err := c.cc.Invoke(ctx, BinaryStorage_ListBinaries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *binaryStorageClient) DeleteBinary(ctx context.Context, in *BinaryRecordID, opts ...grpc.CallOption) (*BinaryEmpty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BinaryEmpty)
	err := c.cc.Invoke(ctx, BinaryStorage_DeleteBinary_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BinaryStorageServer is the server API for BinaryStorage service.
// All implementations must embed UnimplementedBinaryStorageServer
// for forward compatibility.
type BinaryStorageServer interface {
	UploadBinary(grpc.ClientStreamingServer[BinaryChunk, BinaryRecordID]) error
	DownloadBinary(*BinaryRecordID, grpc.ServerStreamingServer[BinaryChunk]) error
	ListBinaries(context.Context, *BinaryEmpty) (*BinaryRecordList, error)
	DeleteBinary(context.Context, *BinaryRecordID) (*BinaryEmpty, error)
	mustEmbedUnimplementedBinaryStorageServer()
}

// UnimplementedBinaryStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBinaryStorageServer struct{}

func (UnimplementedBinaryStorageServer) UploadBinary(grpc.ClientStreamingServer[BinaryChunk, BinaryRecordID]) error {
	return status.Error(codes.Unimplemented, "method UploadBinary not implemented")
}
func (UnimplementedBinaryStorageServer) DownloadBinary(*BinaryRecordID, grpc.ServerStreamingServer[BinaryChunk]) error {
	return status.Error(codes.Unimplemented, "method DownloadBinary not implemented")
}
func (UnimplementedBinaryStorageServer) ListBinaries(context.Context, *BinaryEmpty) (*BinaryRecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListBinaries not implemented")
}
func (UnimplementedBinaryStorageServer) DeleteBinary(context.Context, *BinaryRecordID) (*BinaryEmpty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteBinary not implemented")
}
func (UnimplementedBinaryStorageServer) mustEmbedUnimplementedBinaryStorageServer() {}
func (UnimplementedBinaryStorageServer) testEmbeddedByValue()                       {}

// UnsafeBinaryStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BinaryStorageServer will
// result in compilation errors.
type UnsafeBinaryStorageServer interface {
	mustEmbedUnimplementedBinaryStorageServer()
}

func RegisterBinaryStorageServer(s grpc.ServiceRegistrar, srv BinaryStorageServer) {
	// If the following call panics, it indicates UnimplementedBinaryStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BinaryStorage_ServiceDesc, srv)
}

func _BinaryStorage_UploadBinary_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(BinaryStorageServer).UploadBinary(&grpc.GenericServerStream[BinaryChunk, BinaryRecordID]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryStorage_UploadBinaryServer = grpc.ClientStreamingServer[BinaryChunk, BinaryRecordID]

func _BinaryStorage_DownloadBinary_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BinaryRecordID)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BinaryStorageServer).DownloadBinary(m, &grpc.GenericServerStream[BinaryRecordID, BinaryChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type BinaryStorage_DownloadBinaryServer = grpc.ServerStreamingServer[BinaryChunk]

func _BinaryStorage_ListBinaries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinaryEmpty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinaryStorageServer).ListBinaries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinaryStorage_ListBinaries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinaryStorageServer).ListBinaries(ctx, req.(*BinaryEmpty))
	}
	return interceptor(ctx, in, info, handler)
}

func _BinaryStorage_DeleteBinary_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BinaryRecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BinaryStorageServer).DeleteBinary(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BinaryStorage_DeleteBinary_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BinaryStorageServer).DeleteBinary(ctx, req.(*BinaryRecordID))
	}
	return interceptor(ctx, in, info, handler)
}

// BinaryStorage_ServiceDesc is the grpc.ServiceDesc for BinaryStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BinaryStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.gophkeeper.BinaryStorage",
	HandlerType: (*BinaryStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBinaries",
			Handler:    _BinaryStorage_ListBinaries_Handler,
		},
		{
			MethodName: "DeleteBinary",
			Handler:    _BinaryStorage_DeleteBinary_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UploadBinary",
			Handler:       _BinaryStorage_UploadBinary_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "DownloadBinary",
			Handler:       _BinaryStorage_DownloadBinary_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/binary_storage.proto",
}
