// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/binary_storage.proto

package proto

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BinaryChunk struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data        []byte                 `protobuf:"bytes,1,opt,name=data"`
	xxx_hidden_Nonce       []byte                 `protobuf:"bytes,2,opt,name=nonce"`
	xxx_hidden_Sequence    int32                  `protobuf:"varint,3,opt,name=sequence"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,4,opt,name=metadata"`
	xxx_hidden_IsLast      bool                   `protobuf:"varint,5,opt,name=is_last,json=isLast"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BinaryChunk) Reset() {
	*x = BinaryChunk{}
	mi := &file_api_binary_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryChunk) ProtoMessage() {}

func (x *BinaryChunk) ProtoReflect() protoreflect.Message {
	mi := &file_api_binary_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryChunk) GetData() []byte {
	if x != nil {
		return x.xxx_hidden_Data
	}
	return nil
}

func (x *BinaryChunk) GetNonce() []byte {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *BinaryChunk) GetSequence() int32 {
	if x != nil {
		return x.xxx_hidden_Sequence
	}
	return 0
}

func (x *BinaryChunk) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *BinaryChunk) GetIsLast() bool {
	if x != nil {
		return x.xxx_hidden_IsLast
	}
	return false
}

func (x *BinaryChunk) SetData(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Data = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *BinaryChunk) SetNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Nonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *BinaryChunk) SetSequence(v int32) {
	x.xxx_hidden_Sequence = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *BinaryChunk) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *BinaryChunk) SetIsLast(v bool) {
	x.xxx_hidden_IsLast = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *BinaryChunk) HasData() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BinaryChunk) HasNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BinaryChunk) HasSequence() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *BinaryChunk) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *BinaryChunk) HasIsLast() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *BinaryChunk) ClearData() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Data = nil
}

func (x *BinaryChunk) ClearNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Nonce = nil
}

func (x *BinaryChunk) ClearSequence() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Sequence = 0
}

func (x *BinaryChunk) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Metadata = nil
}

func (x *BinaryChunk) ClearIsLast() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_IsLast = false
}

type BinaryChunk_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Data     []byte
	Nonce    []byte
	Sequence *int32
	Metadata *string
	IsLast   *bool
}

func (b0 BinaryChunk_builder) Build() *BinaryChunk {
	m0 := &BinaryChunk{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Data != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_Data = b.Data
	}
	if b.Nonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Nonce = b.Nonce
	}
	if b.Sequence != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_Sequence = *b.Sequence
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_Metadata = b.Metadata
	}
	if b.IsLast != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_IsLast = *b.IsLast
	}
	return m0
}

type BinaryRecordID struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BinaryRecordID) Reset() {
	*x = BinaryRecordID{}
	mi := &file_api_binary_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryRecordID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryRecordID) ProtoMessage() {}

func (x *BinaryRecordID) ProtoReflect() protoreflect.Message {
	mi := &file_api_binary_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryRecordID) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *BinaryRecordID) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *BinaryRecordID) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BinaryRecordID) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type BinaryRecordID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int32
}

func (b0 BinaryRecordID_builder) Build() *BinaryRecordID {
	m0 := &BinaryRecordID{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type BinaryRecordInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,2,opt,name=metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *BinaryRecordInfo) Reset() {
	*x = BinaryRecordInfo{}
	mi := &file_api_binary_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryRecordInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryRecordInfo) ProtoMessage() {}

func (x *BinaryRecordInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_binary_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryRecordInfo) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *BinaryRecordInfo) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *BinaryRecordInfo) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 2)
}

func (x *BinaryRecordInfo) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *BinaryRecordInfo) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *BinaryRecordInfo) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *BinaryRecordInfo) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *BinaryRecordInfo) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Metadata = nil
}

type BinaryRecordInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id       *int32
	Metadata *string
}

func (b0 BinaryRecordInfo_builder) Build() *BinaryRecordInfo {
	m0 := &BinaryRecordInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 2)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_Metadata = b.Metadata
	}
	return m0
}

type BinaryRecordList struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*BinaryRecordInfo   `protobuf:"bytes,1,rep,name=records"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *BinaryRecordList) Reset() {
	*x = BinaryRecordList{}
	mi := &file_api_binary_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryRecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryRecordList) ProtoMessage() {}

func (x *BinaryRecordList) ProtoReflect() protoreflect.Message {
	mi := &file_api_binary_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *BinaryRecordList) GetRecords() []*BinaryRecordInfo {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *BinaryRecordList) SetRecords(v []*BinaryRecordInfo) {
	x.xxx_hidden_Records = &v
}

type BinaryRecordList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*BinaryRecordInfo
}

func (b0 BinaryRecordList_builder) Build() *BinaryRecordList {
	m0 := &BinaryRecordList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

type BinaryEmpty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BinaryEmpty) Reset() {
	*x = BinaryEmpty{}
	mi := &file_api_binary_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BinaryEmpty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BinaryEmpty) ProtoMessage() {}

func (x *BinaryEmpty) ProtoReflect() protoreflect.Message {
	mi := &file_api_binary_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type BinaryEmpty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 BinaryEmpty_builder) Build() *BinaryEmpty {
	m0 := &BinaryEmpty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_binary_storage_proto protoreflect.FileDescriptor

const file_api_binary_storage_proto_rawDesc = "" +
	"\n" +
	"\x18api/binary_storage.proto\x12\x12storage.gophkeeper\"\x88\x01\n" +
	"\vBinaryChunk\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1a\n" +
	"\bsequence\x18\x03 \x01(\x05R\bsequence\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\x12\x17\n" +
	"\ais_last\x18\x05 \x01(\bR\x06isLast\" \n" +
	"\x0eBinaryRecordID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\">\n" +
	"\x10BinaryRecordInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"R\n" +
	"\x10BinaryRecordList\x12>\n" +
	"\arecords\x18\x01 \x03(\v2$.storage.gophkeeper.BinaryRecordInfoR\arecords\"\r\n" +
	"\vBinaryEmpty2\xf3\x02\n" +
	"\rBinaryStorage\x12W\n" +
	"\fUploadBinary\x12\x1f.storage.gophkeeper.BinaryChunk\x1a\".storage.gophkeeper.BinaryRecordID\"\x00(\x01\x12Y\n" +
	"\x0eDownloadBinary\x12\".storage.gophkeeper.BinaryRecordID\x1a\x1f.storage.gophkeeper.BinaryChunk\"\x000\x01\x12W\n" +
	"\fListBinaries\x12\x1f.storage.gophkeeper.BinaryEmpty\x1a$.storage.gophkeeper.BinaryRecordList\"\x00\x12U\n" +
	"\fDeleteBinary\x12\".storage.gophkeeper.BinaryRecordID\x1a\x1f.storage.gophkeeper.BinaryEmpty\"\x00B\x1bZ\x19gophkeeper/internal/protob\beditionsp\xe8\a"

var file_api_binary_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_binary_storage_proto_goTypes = []any{
	(*BinaryChunk)(nil),      // 0: storage.gophkeeper.BinaryChunk
	(*BinaryRecordID)(nil),   // 1: storage.gophkeeper.BinaryRecordID
	(*BinaryRecordInfo)(nil), // 2: storage.gophkeeper.BinaryRecordInfo
	(*BinaryRecordList)(nil), // 3: storage.gophkeeper.BinaryRecordList
	(*BinaryEmpty)(nil),      // 4: storage.gophkeeper.BinaryEmpty
}
var file_api_binary_storage_proto_depIdxs = []int32{
	2, // 0: storage.gophkeeper.BinaryRecordList.records:type_name -> storage.gophkeeper.BinaryRecordInfo
	0, // 1: storage.gophkeeper.BinaryStorage.UploadBinary:input_type -> storage.gophkeeper.BinaryChunk
	1, // 2: storage.gophkeeper.BinaryStorage.DownloadBinary:input_type -> storage.gophkeeper.BinaryRecordID
	4, // 3: storage.gophkeeper.BinaryStorage.ListBinaries:input_type -> storage.gophkeeper.BinaryEmpty
	1, // 4: storage.gophkeeper.BinaryStorage.DeleteBinary:input_type -> storage.gophkeeper.BinaryRecordID
	1, // 5: storage.gophkeeper.BinaryStorage.UploadBinary:output_type -> storage.gophkeeper.BinaryRecordID
	0, // 6: storage.gophkeeper.BinaryStorage.DownloadBinary:output_type -> storage.gophkeeper.BinaryChunk
	3, // 7: storage.gophkeeper.BinaryStorage.ListBinaries:output_type -> storage.gophkeeper.BinaryRecordList
	4, // 8: storage.gophkeeper.BinaryStorage.DeleteBinary:output_type -> storage.gophkeeper.BinaryEmpty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_binary_storage_proto_init() }
func file_api_binary_storage_proto_init() {
	if File_api_binary_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_binary_storage_proto_rawDesc), len(file_api_binary_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_binary_storage_proto_goTypes,
		DependencyIndexes: file_api_binary_storage_proto_depIdxs,
		MessageInfos:      file_api_binary_storage_proto_msgTypes,
	}.Build()
	File_api_binary_storage_proto = out.File
	file_api_binary_storage_proto_goTypes = nil
	file_api_binary_storage_proto_depIdxs = nil
}
