// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/db_storage.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecureStorage_StoreCard_FullMethodName         = "/storage.gophkeeper.SecureStorage/StoreCard"
	SecureStorage_GetCard_FullMethodName           = "/storage.gophkeeper.SecureStorage/GetCard"
	SecureStorage_ListCards_FullMethodName         = "/storage.gophkeeper.SecureStorage/ListCards"
	SecureStorage_DeleteCard_FullMethodName        = "/storage.gophkeeper.SecureStorage/DeleteCard"
	SecureStorage_StoreCredentials_FullMethodName  = "/storage.gophkeeper.SecureStorage/StoreCredentials"
	SecureStorage_GetCredentials_FullMethodName    = "/storage.gophkeeper.SecureStorage/GetCredentials"
	SecureStorage_ListCredentials_FullMethodName   = "/storage.gophkeeper.SecureStorage/ListCredentials"
	SecureStorage_DeleteCredentials_FullMethodName = "/storage.gophkeeper.SecureStorage/DeleteCredentials"
)

// SecureStorageClient is the client API for SecureStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecureStorageClient interface {
	// Card methods
	StoreCard(ctx context.Context, in *Card, opts ...grpc.CallOption) (*RecordID, error)
	GetCard(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Card, error)
	ListCards(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecordList, error)
	DeleteCard(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Empty, error)
	// login/password methods
	StoreCredentials(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*RecordID, error)
	GetCredentials(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Credentials, error)
	ListCredentials(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecordList, error)
	DeleteCredentials(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Empty, error)
}

type secureStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewSecureStorageClient(cc grpc.ClientConnInterface) SecureStorageClient {
	return &secureStorageClient{cc}
}

func (c *secureStorageClient) StoreCard(ctx context.Context, in *Card, opts ...grpc.CallOption) (*RecordID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordID)
	err := c.cc.Invoke(ctx, SecureStorage_StoreCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) GetCard(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Card, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Card)
	err := c.cc.Invoke(ctx, SecureStorage_GetCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) ListCards(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, SecureStorage_ListCards_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) DeleteCard(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SecureStorage_DeleteCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) StoreCredentials(ctx context.Context, in *Credentials, opts ...grpc.CallOption) (*RecordID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordID)
	err := c.cc.Invoke(ctx, SecureStorage_StoreCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) GetCredentials(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Credentials, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Credentials)
	err := c.cc.Invoke(ctx, SecureStorage_GetCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) ListCredentials(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, SecureStorage_ListCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) DeleteCredentials(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SecureStorage_DeleteCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecureStorageServer is the server API for SecureStorage service.
// All implementations must embed UnimplementedSecureStorageServer
// for forward compatibility.
type SecureStorageServer interface {
	// Card methods
	StoreCard(context.Context, *Card) (*RecordID, error)
	GetCard(context.Context, *RecordID) (*Card, error)
	ListCards(context.Context, *Empty) (*RecordList, error)
	DeleteCard(context.Context, *RecordID) (*Empty, error)
	// login/password methods
	StoreCredentials(context.Context, *Credentials) (*RecordID, error)
	GetCredentials(context.Context, *RecordID) (*Credentials, error)
	ListCredentials(context.Context, *Empty) (*RecordList, error)
	DeleteCredentials(context.Context, *RecordID) (*Empty, error)
	mustEmbedUnimplementedSecureStorageServer()
}

// UnimplementedSecureStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecureStorageServer struct{}

func (UnimplementedSecureStorageServer) StoreCard(context.Context, *Card) (*RecordID, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreCard not implemented")
}
func (UnimplementedSecureStorageServer) GetCard(context.Context, *RecordID) (*Card, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCard not implemented")
}
func (UnimplementedSecureStorageServer) ListCards(context.Context, *Empty) (*RecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCards not implemented")
}
func (UnimplementedSecureStorageServer) DeleteCard(context.Context, *RecordID) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCard not implemented")
}
func (UnimplementedSecureStorageServer) StoreCredentials(context.Context, *Credentials) (*RecordID, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreCredentials not implemented")
}
func (UnimplementedSecureStorageServer) GetCredentials(context.Context, *RecordID) (*Credentials, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCredentials not implemented")
}
func (UnimplementedSecureStorageServer) ListCredentials(context.Context, *Empty) (*RecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListCredentials not implemented")
}
func (UnimplementedSecureStorageServer) DeleteCredentials(context.Context, *RecordID) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCredentials not implemented")
}
func (UnimplementedSecureStorageServer) mustEmbedUnimplementedSecureStorageServer() {}
func (UnimplementedSecureStorageServer) testEmbeddedByValue()                       {}

// UnsafeSecureStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecureStorageServer will
// result in compilation errors.
type UnsafeSecureStorageServer interface {
	mustEmbedUnimplementedSecureStorageServer()
}

func RegisterSecureStorageServer(s grpc.ServiceRegistrar, srv SecureStorageServer) {
	// If the following call panics, it indicates UnimplementedSecureStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecureStorage_ServiceDesc, srv)
}

func _SecureStorage_StoreCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Card)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).StoreCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_StoreCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).StoreCard(ctx, req.(*Card))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_GetCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).GetCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_GetCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).GetCard(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_ListCards_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).ListCards(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_ListCards_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).ListCards(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_DeleteCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).DeleteCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_DeleteCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).DeleteCard(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_StoreCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Credentials)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).StoreCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_StoreCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).StoreCredentials(ctx, req.(*Credentials))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_GetCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).GetCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_GetCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).GetCredentials(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_ListCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).ListCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_ListCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).ListCredentials(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_DeleteCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).DeleteCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_DeleteCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).DeleteCredentials(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

// SecureStorage_ServiceDesc is the grpc.ServiceDesc for SecureStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecureStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.gophkeeper.SecureStorage",
	HandlerType: (*SecureStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreCard",
			Handler:    _SecureStorage_StoreCard_Handler,
		},
		{
			MethodName: "GetCard",
			Handler:    _SecureStorage_GetCard_Handler,
		},
		{
			MethodName: "ListCards",
			Handler:    _SecureStorage_ListCards_Handler,
		},
		{
			MethodName: "DeleteCard",
			Handler:    _SecureStorage_DeleteCard_Handler,
		},
		{
			MethodName: "StoreCredentials",
			Handler:    _SecureStorage_StoreCredentials_Handler,
		},
		{
			MethodName: "GetCredentials",
			Handler:    _SecureStorage_GetCredentials_Handler,
		},
		{
			MethodName: "ListCredentials",
			Handler:    _SecureStorage_ListCredentials_Handler,
		},
		{
			MethodName: "DeleteCredentials",
			Handler:    _SecureStorage_DeleteCredentials_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/db_storage.proto",
}
