// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/db_storage.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Card struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_CardNumber  *string                `protobuf:"bytes,1,opt,name=card_number,json=cardNumber"`
	xxx_hidden_Cvv         *string                `protobuf:"bytes,2,opt,name=cvv"`
	xxx_hidden_CardHolder  *string                `protobuf:"bytes,3,opt,name=card_holder,json=cardHolder"`
	xxx_hidden_ExpiryDate  *string                `protobuf:"bytes,4,opt,name=expiry_date,json=expiryDate"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,5,opt,name=metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Card) Reset() {
	*x = Card{}
	mi := &file_api_db_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Card) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Card) ProtoMessage() {}

func (x *Card) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Card) GetCardNumber() string {
	if x != nil {
		if x.xxx_hidden_CardNumber != nil {
			return *x.xxx_hidden_CardNumber
		}
		return ""
	}
	return ""
}

func (x *Card) GetCvv() string {
	if x != nil {
		if x.xxx_hidden_Cvv != nil {
			return *x.xxx_hidden_Cvv
		}
		return ""
	}
	return ""
}

func (x *Card) GetCardHolder() string {
	if x != nil {
		if x.xxx_hidden_CardHolder != nil {
			return *x.xxx_hidden_CardHolder
		}
		return ""
	}
	return ""
}

func (x *Card) GetExpiryDate() string {
	if x != nil {
		if x.xxx_hidden_ExpiryDate != nil {
			return *x.xxx_hidden_ExpiryDate
		}
		return ""
	}
	return ""
}

func (x *Card) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *Card) SetCardNumber(v string) {
	x.xxx_hidden_CardNumber = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 5)
}

func (x *Card) SetCvv(v string) {
	x.xxx_hidden_Cvv = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 5)
}

func (x *Card) SetCardHolder(v string) {
	x.xxx_hidden_CardHolder = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 5)
}

func (x *Card) SetExpiryDate(v string) {
	x.xxx_hidden_ExpiryDate = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 5)
}

func (x *Card) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 4, 5)
}

func (x *Card) HasCardNumber() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Card) HasCvv() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Card) HasCardHolder() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Card) HasExpiryDate() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Card) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 4)
}

func (x *Card) ClearCardNumber() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_CardNumber = nil
}

func (x *Card) ClearCvv() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Cvv = nil
}

func (x *Card) ClearCardHolder() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_CardHolder = nil
}

func (x *Card) ClearExpiryDate() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_ExpiryDate = nil
}

func (x *Card) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 4)
	x.xxx_hidden_Metadata = nil
}

type Card_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	CardNumber *string
	Cvv        *string
	CardHolder *string
	ExpiryDate *string
	Metadata   *string
}

func (b0 Card_builder) Build() *Card {
	m0 := &Card{}
	b, x := &b0, m0
	_, _ = b, x
	if b.CardNumber != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 5)
		x.xxx_hidden_CardNumber = b.CardNumber
	}
	if b.Cvv != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 5)
		x.xxx_hidden_Cvv = b.Cvv
	}
	if b.CardHolder != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 5)
		x.xxx_hidden_CardHolder = b.CardHolder
	}
	if b.ExpiryDate != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 5)
		x.xxx_hidden_ExpiryDate = b.ExpiryDate
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 4, 5)
		x.xxx_hidden_Metadata = b.Metadata
	}
	return m0
}

type Credentials struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Username    *string                `protobuf:"bytes,1,opt,name=username"`
	xxx_hidden_Password    *string                `protobuf:"bytes,2,opt,name=password"`
	xxx_hidden_ServiceName *string                `protobuf:"bytes,3,opt,name=service_name,json=serviceName"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,4,opt,name=metadata"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *Credentials) Reset() {
	*x = Credentials{}
	mi := &file_api_db_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Credentials) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Credentials) ProtoMessage() {}

func (x *Credentials) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Credentials) GetUsername() string {
	if x != nil {
		if x.xxx_hidden_Username != nil {
			return *x.xxx_hidden_Username
		}
		return ""
	}
	return ""
}

func (x *Credentials) GetPassword() string {
	if x != nil {
		if x.xxx_hidden_Password != nil {
			return *x.xxx_hidden_Password
		}
		return ""
	}
	return ""
}

func (x *Credentials) GetServiceName() string {
	if x != nil {
		if x.xxx_hidden_ServiceName != nil {
			return *x.xxx_hidden_ServiceName
		}
		return ""
	}
	return ""
}

func (x *Credentials) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *Credentials) SetUsername(v string) {
	x.xxx_hidden_Username = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *Credentials) SetPassword(v string) {
	x.xxx_hidden_Password = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *Credentials) SetServiceName(v string) {
	x.xxx_hidden_ServiceName = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *Credentials) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *Credentials) HasUsername() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *Credentials) HasPassword() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Credentials) HasServiceName() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *Credentials) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *Credentials) ClearUsername() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Username = nil
}

func (x *Credentials) ClearPassword() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Password = nil
}

func (x *Credentials) ClearServiceName() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_ServiceName = nil
}

func (x *Credentials) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_Metadata = nil
}

type Credentials_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Username    *string
	Password    *string
	ServiceName *string
	Metadata    *string
}

func (b0 Credentials_builder) Build() *Credentials {
	m0 := &Credentials{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Username != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Username = b.Username
	}
	if b.Password != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Password = b.Password
	}
	if b.ServiceName != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_ServiceName = b.ServiceName
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_Metadata = b.Metadata
	}
	return m0
}

type RecordID struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecordID) Reset() {
	*x = RecordID{}
	mi := &file_api_db_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordID) ProtoMessage() {}

func (x *RecordID) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordID) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *RecordID) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RecordID) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecordID) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type RecordID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int32
}

func (b0 RecordID_builder) Build() *RecordID {
	m0 := &RecordID{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type RecordList struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*RecordID           `protobuf:"bytes,1,rep,name=records"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_api_db_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordList) GetRecords() []*RecordID {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *RecordList) SetRecords(v []*RecordID) {
	x.xxx_hidden_Records = &v
}

type RecordList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*RecordID
}

func (b0 RecordList_builder) Build() *RecordList {
	m0 := &RecordList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_db_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_db_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Empty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Empty_builder) Build() *Empty {
	m0 := &Empty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_db_storage_proto protoreflect.FileDescriptor

const file_api_db_storage_proto_rawDesc = "" +
	"\n" +
	"\x14api/db_storage.proto\x12\x12storage.gophkeeper\"\x97\x01\n" +
	"\x04Card\x12\x1f\n" +
	"\vcard_number\x18\x01 \x01(\tR\n" +
	"cardNumber\x12\x10\n" +
	"\x03cvv\x18\x02 \x01(\tR\x03cvv\x12\x1f\n" +
	"\vcard_holder\x18\x03 \x01(\tR\n" +
	"cardHolder\x12\x1f\n" +
	"\vexpiry_date\x18\x04 \x01(\tR\n" +
	"expiryDate\x12\x1a\n" +
	"\bmetadata\x18\x05 \x01(\tR\bmetadata\"\x84\x01\n" +
	"\vCredentials\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12!\n" +
	"\fservice_name\x18\x03 \x01(\tR\vserviceName\x12\x1a\n" +
	"\bmetadata\x18\x04 \x01(\tR\bmetadata\"\x1a\n" +
	"\bRecordID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"D\n" +
	"\n" +
	"RecordList\x126\n" +
	"\arecords\x18\x01 \x03(\v2\x1c.storage.gophkeeper.RecordIDR\arecords\"\a\n" +
	"\x05Empty2\xf6\x04\n" +
	"\rSecureStorage\x12E\n" +
	"\tStoreCard\x12\x18.storage.gophkeeper.Card\x1a\x1c.storage.gophkeeper.RecordID\"\x00\x12C\n" +
	"\aGetCard\x12\x1c.storage.gophkeeper.RecordID\x1a\x18.storage.gophkeeper.Card\"\x00\x12H\n" +
	"\tListCards\x12\x19.storage.gophkeeper.Empty\x1a\x1e.storage.gophkeeper.RecordList\"\x00\x12G\n" +
	"\n" +
	"DeleteCard\x12\x1c.storage.gophkeeper.RecordID\x1a\x19.storage.gophkeeper.Empty\"\x00\x12S\n" +
	"\x10StoreCredentials\x12\x1f.storage.gophkeeper.Credentials\x1a\x1c.storage.gophkeeper.RecordID\"\x00\x12Q\n" +
	"\x0eGetCredentials\x12\x1c.storage.gophkeeper.RecordID\x1a\x1f.storage.gophkeeper.Credentials\"\x00\x12N\n" +
	"\x0fListCredentials\x12\x19.storage.gophkeeper.Empty\x1a\x1e.storage.gophkeeper.RecordList\"\x00\x12N\n" +
	"\x11DeleteCredentials\x12\x1c.storage.gophkeeper.RecordID\x1a\x19.storage.gophkeeper.Empty\"\x00B\x1bZ\x19gophkeeper/internal/protob\beditionsp\xe8\a"

var file_api_db_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_db_storage_proto_goTypes = []any{
	(*Card)(nil),        // 0: storage.gophkeeper.Card
	(*Credentials)(nil), // 1: storage.gophkeeper.Credentials
	(*RecordID)(nil),    // 2: storage.gophkeeper.RecordID
	(*RecordList)(nil),  // 3: storage.gophkeeper.RecordList
	(*Empty)(nil),       // 4: storage.gophkeeper.Empty
}
var file_api_db_storage_proto_depIdxs = []int32{
	2, // 0: storage.gophkeeper.RecordList.records:type_name -> storage.gophkeeper.RecordID
	0, // 1: storage.gophkeeper.SecureStorage.StoreCard:input_type -> storage.gophkeeper.Card
	2, // 2: storage.gophkeeper.SecureStorage.GetCard:input_type -> storage.gophkeeper.RecordID
	4, // 3: storage.gophkeeper.SecureStorage.ListCards:input_type -> storage.gophkeeper.Empty
	2, // 4: storage.gophkeeper.SecureStorage.DeleteCard:input_type -> storage.gophkeeper.RecordID
	1, // 5: storage.gophkeeper.SecureStorage.StoreCredentials:input_type -> storage.gophkeeper.Credentials
	2, // 6: storage.gophkeeper.SecureStorage.GetCredentials:input_type -> storage.gophkeeper.RecordID
	4, // 7: storage.gophkeeper.SecureStorage.ListCredentials:input_type -> storage.gophkeeper.Empty
	2, // 8: storage.gophkeeper.SecureStorage.DeleteCredentials:input_type -> storage.gophkeeper.RecordID
	2, // 9: storage.gophkeeper.SecureStorage.StoreCard:output_type -> storage.gophkeeper.RecordID
	0, // 10: storage.gophkeeper.SecureStorage.GetCard:output_type -> storage.gophkeeper.Card
	3, // 11: storage.gophkeeper.SecureStorage.ListCards:output_type -> storage.gophkeeper.RecordList
	4, // 12: storage.gophkeeper.SecureStorage.DeleteCard:output_type -> storage.gophkeeper.Empty
	2, // 13: storage.gophkeeper.SecureStorage.StoreCredentials:output_type -> storage.gophkeeper.RecordID
	1, // 14: storage.gophkeeper.SecureStorage.GetCredentials:output_type -> storage.gophkeeper.Credentials
	3, // 15: storage.gophkeeper.SecureStorage.ListCredentials:output_type -> storage.gophkeeper.RecordList
	4, // 16: storage.gophkeeper.SecureStorage.DeleteCredentials:output_type -> storage.gophkeeper.Empty
	9, // [9:17] is the sub-list for method output_type
	1, // [1:9] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_db_storage_proto_init() }
func file_api_db_storage_proto_init() {
	if File_api_db_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_db_storage_proto_rawDesc), len(file_api_db_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_db_storage_proto_goTypes,
		DependencyIndexes: file_api_db_storage_proto_depIdxs,
		MessageInfos:      file_api_db_storage_proto_msgTypes,
	}.Build()
	File_api_db_storage_proto = out.File
	file_api_db_storage_proto_goTypes = nil
	file_api_db_storage_proto_depIdxs = nil
}
