// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: api/secure_storage.proto

package proto

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SecureStorage_StoreRecord_FullMethodName  = "/storage.gophkeeper.SecureStorage/StoreRecord"
	SecureStorage_GetRecord_FullMethodName    = "/storage.gophkeeper.SecureStorage/GetRecord"
	SecureStorage_ListRecords_FullMethodName  = "/storage.gophkeeper.SecureStorage/ListRecords"
	SecureStorage_DeleteRecord_FullMethodName = "/storage.gophkeeper.SecureStorage/DeleteRecord"
)

// SecureStorageClient is the client API for SecureStorage service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SecureStorageClient interface {
	StoreRecord(ctx context.Context, in *EncryptedRecord, opts ...grpc.CallOption) (*RecordID, error)
	GetRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*EncryptedRecord, error)
	ListRecords(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*RecordList, error)
	DeleteRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Empty, error)
}

type secureStorageClient struct {
	cc grpc.ClientConnInterface
}

func NewSecureStorageClient(cc grpc.ClientConnInterface) SecureStorageClient {
	return &secureStorageClient{cc}
}

func (c *secureStorageClient) StoreRecord(ctx context.Context, in *EncryptedRecord, opts ...grpc.CallOption) (*RecordID, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordID)
	err := c.cc.Invoke(ctx, SecureStorage_StoreRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) GetRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*EncryptedRecord, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptedRecord)
	err := c.cc.Invoke(ctx, SecureStorage_GetRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) ListRecords(ctx context.Context, in *ListRequest, opts ...grpc.CallOption) (*RecordList, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordList)
	err := c.cc.Invoke(ctx, SecureStorage_ListRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *secureStorageClient) DeleteRecord(ctx context.Context, in *RecordID, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, SecureStorage_DeleteRecord_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SecureStorageServer is the server API for SecureStorage service.
// All implementations must embed UnimplementedSecureStorageServer
// for forward compatibility.
type SecureStorageServer interface {
	StoreRecord(context.Context, *EncryptedRecord) (*RecordID, error)
	GetRecord(context.Context, *RecordID) (*EncryptedRecord, error)
	ListRecords(context.Context, *ListRequest) (*RecordList, error)
	DeleteRecord(context.Context, *RecordID) (*Empty, error)
	mustEmbedUnimplementedSecureStorageServer()
}

// UnimplementedSecureStorageServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSecureStorageServer struct{}

func (UnimplementedSecureStorageServer) StoreRecord(context.Context, *EncryptedRecord) (*RecordID, error) {
	return nil, status.Error(codes.Unimplemented, "method StoreRecord not implemented")
}
func (UnimplementedSecureStorageServer) GetRecord(context.Context, *RecordID) (*EncryptedRecord, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecord not implemented")
}
func (UnimplementedSecureStorageServer) ListRecords(context.Context, *ListRequest) (*RecordList, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRecords not implemented")
}
func (UnimplementedSecureStorageServer) DeleteRecord(context.Context, *RecordID) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRecord not implemented")
}
func (UnimplementedSecureStorageServer) mustEmbedUnimplementedSecureStorageServer() {}
func (UnimplementedSecureStorageServer) testEmbeddedByValue()                       {}

// UnsafeSecureStorageServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SecureStorageServer will
// result in compilation errors.
type UnsafeSecureStorageServer interface {
	mustEmbedUnimplementedSecureStorageServer()
}

func RegisterSecureStorageServer(s grpc.ServiceRegistrar, srv SecureStorageServer) {
	// If the following call panics, it indicates UnimplementedSecureStorageServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SecureStorage_ServiceDesc, srv)
}

func _SecureStorage_StoreRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptedRecord)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).StoreRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_StoreRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).StoreRecord(ctx, req.(*EncryptedRecord))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_GetRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).GetRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_GetRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).GetRecord(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_ListRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).ListRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_ListRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).ListRecords(ctx, req.(*ListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SecureStorage_DeleteRecord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SecureStorageServer).DeleteRecord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SecureStorage_DeleteRecord_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SecureStorageServer).DeleteRecord(ctx, req.(*RecordID))
	}
	return interceptor(ctx, in, info, handler)
}

// SecureStorage_ServiceDesc is the grpc.ServiceDesc for SecureStorage service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SecureStorage_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "storage.gophkeeper.SecureStorage",
	HandlerType: (*SecureStorageServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StoreRecord",
			Handler:    _SecureStorage_StoreRecord_Handler,
		},
		{
			MethodName: "GetRecord",
			Handler:    _SecureStorage_GetRecord_Handler,
		},
		{
			MethodName: "ListRecords",
			Handler:    _SecureStorage_ListRecords_Handler,
		},
		{
			MethodName: "DeleteRecord",
			Handler:    _SecureStorage_DeleteRecord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/secure_storage.proto",
}
