// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: api/secure_storage.proto

package proto

import (
	reflect "reflect"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptedRecord struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Ciphertext  []byte                 `protobuf:"bytes,1,opt,name=ciphertext"`
	xxx_hidden_Nonce       []byte                 `protobuf:"bytes,2,opt,name=nonce"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,3,opt,name=metadata"`
	xxx_hidden_RecordType  *string                `protobuf:"bytes,4,opt,name=record_type,json=recordType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *EncryptedRecord) Reset() {
	*x = EncryptedRecord{}
	mi := &file_api_secure_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptedRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptedRecord) ProtoMessage() {}

func (x *EncryptedRecord) ProtoReflect() protoreflect.Message {
	mi := &file_api_secure_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *EncryptedRecord) GetCiphertext() []byte {
	if x != nil {
		return x.xxx_hidden_Ciphertext
	}
	return nil
}

func (x *EncryptedRecord) GetNonce() []byte {
	if x != nil {
		return x.xxx_hidden_Nonce
	}
	return nil
}

func (x *EncryptedRecord) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *EncryptedRecord) GetRecordType() string {
	if x != nil {
		if x.xxx_hidden_RecordType != nil {
			return *x.xxx_hidden_RecordType
		}
		return ""
	}
	return ""
}

func (x *EncryptedRecord) SetCiphertext(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Ciphertext = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *EncryptedRecord) SetNonce(v []byte) {
	if v == nil {
		v = []byte{}
	}
	x.xxx_hidden_Nonce = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 4)
}

func (x *EncryptedRecord) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 4)
}

func (x *EncryptedRecord) SetRecordType(v string) {
	x.xxx_hidden_RecordType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 3, 4)
}

func (x *EncryptedRecord) HasCiphertext() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *EncryptedRecord) HasNonce() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *EncryptedRecord) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *EncryptedRecord) HasRecordType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 3)
}

func (x *EncryptedRecord) ClearCiphertext() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Ciphertext = nil
}

func (x *EncryptedRecord) ClearNonce() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Nonce = nil
}

func (x *EncryptedRecord) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_Metadata = nil
}

func (x *EncryptedRecord) ClearRecordType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 3)
	x.xxx_hidden_RecordType = nil
}

type EncryptedRecord_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Ciphertext []byte
	Nonce      []byte
	Metadata   *string
	RecordType *string
}

func (b0 EncryptedRecord_builder) Build() *EncryptedRecord {
	m0 := &EncryptedRecord{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Ciphertext != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Ciphertext = b.Ciphertext
	}
	if b.Nonce != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 4)
		x.xxx_hidden_Nonce = b.Nonce
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 4)
		x.xxx_hidden_Metadata = b.Metadata
	}
	if b.RecordType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 3, 4)
		x.xxx_hidden_RecordType = b.RecordType
	}
	return m0
}

type RecordID struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecordID) Reset() {
	*x = RecordID{}
	mi := &file_api_secure_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordID) ProtoMessage() {}

func (x *RecordID) ProtoReflect() protoreflect.Message {
	mi := &file_api_secure_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordID) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *RecordID) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *RecordID) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecordID) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

type RecordID_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id *int32
}

func (b0 RecordID_builder) Build() *RecordID {
	m0 := &RecordID{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_Id = *b.Id
	}
	return m0
}

type ListRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_RecordType  *string                `protobuf:"bytes,1,opt,name=record_type,json=recordType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_api_secure_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_secure_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListRequest) GetRecordType() string {
	if x != nil {
		if x.xxx_hidden_RecordType != nil {
			return *x.xxx_hidden_RecordType
		}
		return ""
	}
	return ""
}

func (x *ListRequest) SetRecordType(v string) {
	x.xxx_hidden_RecordType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 1)
}

func (x *ListRequest) HasRecordType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListRequest) ClearRecordType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_RecordType = nil
}

type ListRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	RecordType *string
}

func (b0 ListRequest_builder) Build() *ListRequest {
	m0 := &ListRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.RecordType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 1)
		x.xxx_hidden_RecordType = b.RecordType
	}
	return m0
}

type RecordInfo struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Id          int32                  `protobuf:"varint,1,opt,name=id"`
	xxx_hidden_Metadata    *string                `protobuf:"bytes,2,opt,name=metadata"`
	xxx_hidden_RecordType  *string                `protobuf:"bytes,3,opt,name=record_type,json=recordType"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *RecordInfo) Reset() {
	*x = RecordInfo{}
	mi := &file_api_secure_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordInfo) ProtoMessage() {}

func (x *RecordInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_secure_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordInfo) GetId() int32 {
	if x != nil {
		return x.xxx_hidden_Id
	}
	return 0
}

func (x *RecordInfo) GetMetadata() string {
	if x != nil {
		if x.xxx_hidden_Metadata != nil {
			return *x.xxx_hidden_Metadata
		}
		return ""
	}
	return ""
}

func (x *RecordInfo) GetRecordType() string {
	if x != nil {
		if x.xxx_hidden_RecordType != nil {
			return *x.xxx_hidden_RecordType
		}
		return ""
	}
	return ""
}

func (x *RecordInfo) SetId(v int32) {
	x.xxx_hidden_Id = v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 3)
}

func (x *RecordInfo) SetMetadata(v string) {
	x.xxx_hidden_Metadata = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 3)
}

func (x *RecordInfo) SetRecordType(v string) {
	x.xxx_hidden_RecordType = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 2, 3)
}

func (x *RecordInfo) HasId() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *RecordInfo) HasMetadata() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *RecordInfo) HasRecordType() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 2)
}

func (x *RecordInfo) ClearId() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Id = 0
}

func (x *RecordInfo) ClearMetadata() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_Metadata = nil
}

func (x *RecordInfo) ClearRecordType() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 2)
	x.xxx_hidden_RecordType = nil
}

type RecordInfo_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Id         *int32
	Metadata   *string
	RecordType *string
}

func (b0 RecordInfo_builder) Build() *RecordInfo {
	m0 := &RecordInfo{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Id != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 3)
		x.xxx_hidden_Id = *b.Id
	}
	if b.Metadata != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 3)
		x.xxx_hidden_Metadata = b.Metadata
	}
	if b.RecordType != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 2, 3)
		x.xxx_hidden_RecordType = b.RecordType
	}
	return m0
}

type RecordList struct {
	state              protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Records *[]*RecordInfo         `protobuf:"bytes,1,rep,name=records"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_api_secure_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_api_secure_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *RecordList) GetRecords() []*RecordInfo {
	if x != nil {
		if x.xxx_hidden_Records != nil {
			return *x.xxx_hidden_Records
		}
	}
	return nil
}

func (x *RecordList) SetRecords(v []*RecordInfo) {
	x.xxx_hidden_Records = &v
}

type RecordList_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Records []*RecordInfo
}

func (b0 RecordList_builder) Build() *RecordList {
	m0 := &RecordList{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Records = &b.Records
	return m0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_api_secure_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_api_secure_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type Empty_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 Empty_builder) Build() *Empty {
	m0 := &Empty{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_api_secure_storage_proto protoreflect.FileDescriptor

const file_api_secure_storage_proto_rawDesc = "" +
	"\n" +
	"\x18api/secure_storage.proto\x12\x12storage.gophkeeper\"\x84\x01\n" +
	"\x0fEncryptedRecord\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\fR\n" +
	"ciphertext\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1a\n" +
	"\bmetadata\x18\x03 \x01(\tR\bmetadata\x12\x1f\n" +
	"\vrecord_type\x18\x04 \x01(\tR\n" +
	"recordType\"\x1a\n" +
	"\bRecordID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\".\n" +
	"\vListRequest\x12\x1f\n" +
	"\vrecord_type\x18\x01 \x01(\tR\n" +
	"recordType\"Y\n" +
	"\n" +
	"RecordInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\x12\x1f\n" +
	"\vrecord_type\x18\x03 \x01(\tR\n" +
	"recordType\"F\n" +
	"\n" +
	"RecordList\x128\n" +
	"\arecords\x18\x01 \x03(\v2\x1e.storage.gophkeeper.RecordInfoR\arecords\"\a\n" +
	"\x05Empty2\xd2\x02\n" +
	"\rSecureStorage\x12R\n" +
	"\vStoreRecord\x12#.storage.gophkeeper.EncryptedRecord\x1a\x1c.storage.gophkeeper.RecordID\"\x00\x12P\n" +
	"\tGetRecord\x12\x1c.storage.gophkeeper.RecordID\x1a#.storage.gophkeeper.EncryptedRecord\"\x00\x12P\n" +
	"\vListRecords\x12\x1f.storage.gophkeeper.ListRequest\x1a\x1e.storage.gophkeeper.RecordList\"\x00\x12I\n" +
	"\fDeleteRecord\x12\x1c.storage.gophkeeper.RecordID\x1a\x19.storage.gophkeeper.Empty\"\x00B\x1bZ\x19gophkeeper/internal/protob\beditionsp\xe8\a"

var file_api_secure_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_api_secure_storage_proto_goTypes = []any{
	(*EncryptedRecord)(nil), // 0: storage.gophkeeper.EncryptedRecord
	(*RecordID)(nil),        // 1: storage.gophkeeper.RecordID
	(*ListRequest)(nil),     // 2: storage.gophkeeper.ListRequest
	(*RecordInfo)(nil),      // 3: storage.gophkeeper.RecordInfo
	(*RecordList)(nil),      // 4: storage.gophkeeper.RecordList
	(*Empty)(nil),           // 5: storage.gophkeeper.Empty
}
var file_api_secure_storage_proto_depIdxs = []int32{
	3, // 0: storage.gophkeeper.RecordList.records:type_name -> storage.gophkeeper.RecordInfo
	0, // 1: storage.gophkeeper.SecureStorage.StoreRecord:input_type -> storage.gophkeeper.EncryptedRecord
	1, // 2: storage.gophkeeper.SecureStorage.GetRecord:input_type -> storage.gophkeeper.RecordID
	2, // 3: storage.gophkeeper.SecureStorage.ListRecords:input_type -> storage.gophkeeper.ListRequest
	1, // 4: storage.gophkeeper.SecureStorage.DeleteRecord:input_type -> storage.gophkeeper.RecordID
	1, // 5: storage.gophkeeper.SecureStorage.StoreRecord:output_type -> storage.gophkeeper.RecordID
	0, // 6: storage.gophkeeper.SecureStorage.GetRecord:output_type -> storage.gophkeeper.EncryptedRecord
	4, // 7: storage.gophkeeper.SecureStorage.ListRecords:output_type -> storage.gophkeeper.RecordList
	5, // 8: storage.gophkeeper.SecureStorage.DeleteRecord:output_type -> storage.gophkeeper.Empty
	5, // [5:9] is the sub-list for method output_type
	1, // [1:5] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_secure_storage_proto_init() }
func file_api_secure_storage_proto_init() {
	if File_api_secure_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_secure_storage_proto_rawDesc), len(file_api_secure_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_secure_storage_proto_goTypes,
		DependencyIndexes: file_api_secure_storage_proto_depIdxs,
		MessageInfos:      file_api_secure_storage_proto_msgTypes,
	}.Build()
	File_api_secure_storage_proto = out.File
	file_api_secure_storage_proto_goTypes = nil
	file_api_secure_storage_proto_depIdxs = nil
}
