CREATE TABLE creds (
	id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
	login VARCHAR(128) NOT NULL UNIQUE,
    password VARCHAR(256) NOT NULL,
    service_name VARCHAR(128) NOT NULL,
    metadata VARCHAR(64),
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
);