CREATE TABLE binary_records (
    id INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    s3_key TEXT NOT NULL UNIQUE,
    metadata TEXT NOT NULL DEFAULT '',
    user_id INT NOT NULL REFERENCES users(id) ON DELETE CASCADE
);
